applications:
  - prometheus
parameters:
  prometheus:
    alertmanager:
      enabled: true
      dir:
        config: /srv/volumes/prometheus/alertmanager
        data: /srv/volumes/local/prometheus/alertmanager
      bind:
        address: 0.0.0.0
        port: 9093
      config:
        global:
          resolve_timeout: 5m
        route:
          group_by: ['region', 'service']
          group_wait: 60s
          group_interval: 5m
          repeat_interval: 3h
          receiver: default
        inhibit_rule:
          InhibitCriticalWhenDown:
            enabled: false
            source_match:
              severity: 'down'
            target_match:
              severity: 'critical'
            equal: ['region', 'service']
          InhibitWarningWhenDown:
            enabled: false
            source_match:
              severity: 'down'
            target_match:
              severity: 'warning'
            equal: ['region', 'service']
          InhibitWarningWhenCritical:
            enabled: false
            source_match:
              severity: 'critical'
            target_match:
              severity: 'warning'
            equal: ['region', 'service']
        receiver:
          default:
            enabled: true
